### ISSUE TITLE
Feature request: Implement extension network request blocking

### ISSUE THREAD

**Issue by jamesdwilson** [dnakov/little-rat#1]
Overview:
The extension currently reports on network requests made by other installed extensions, similar to ObjectiveSee's LuLu firewall for macOS. This feature request is to add blocking capabilities like LuLu, allowing users to prevent specific extensions from sending data without approval.
Requirements:
- Allow users to toggle on/off a "Block extension requests" mode
- Provide interfaces for selecting extensions to block, like LuLu's allowlisting
- When enabled, block network requests initiated by blocked extensions
- Provide visible alerts when a blocked request is attempted
- Integrate reporting to log all blocked requests
Benefits:
- Increased user control over extension network access
- Ability to restrict suspicious/malicious extensions like LuLu
- Improved privacy by limiting unapproved communications
- Provides firewall-like security for browser extensions
Risks/Considerations:
- Could break functionality of extensions needing network access
- Need to validate blocking avoids bypasses
- Large volume of blocked requests could impact browser performance
- UI for selecting blocked extensions should be simple and clear
- May receive support requests if needed extension is blocked

**Comment by dnakov** [comment]
Thank you, this is a great list. I'd love to build this but since the extension might not be allowed on the chrome store, I'd prefer to keep it as simple as possible so that people can easily check the code before installing it manually.
I'll close it for now and reopen if it makes it to the store.

**Comment by jamesdwilson** [comment]
@dnakov not to sound ungrateful but does this mean you're not interested in any further development at this time?

**Comment by dnakov** [comment]
I am interested, just that I won't be looking into it in the next couple of weeks. 
I'm going to fix some bugs and try to see if I can get it to the chrome store first. 

Here is my immediate list:
* fix bugs (couple of open issues)
* fix styling (long URLs for example)
* automated github actions for crx release
* Marketing stuff, screenshots, etc for another chrome store release attempt. (Even though it uses an API that's supposedly not for chrome distribution, I still want to try)

PRs for any new functionality are welcome, but I'd like to keep things as simple as possible and avoid using any bundlers, etc.
Also, some of the features you outlined would require dynamic rules and I just haven't delved into them enough to determine what it could look like.

**Comment by jamesdwilson** [comment]
I see. Thanks again for your work on this. Very innovative idea. Kudos. I was thinking of forking it or perhaps you'd want to make two branches? This is a common strategy. a Store version and a non-store version.

**Comment by dnakov** [comment]
Reopening this to keep thinking/talking about it

**Comment by dnakov** [comment]
Started adding some blocking functionality in the https://github.com/dnakov/little-rat/tree/next branch if anyone wants to check it out
<img width="404" alt="Screenshot 2023-08-17 at 7 15 41 PM" src="https://github.com/dnakov/little-rat/assets/3777433/be7d9072-e28b-4579-9b18-ea63f7aacdab">

**Comment by dnakov** [comment]
This is now in main, thanks for all your feedback.
If I missed something, feel free to open a new issue
