### ISSUE TITLE
Does blocking by URL actually work?

### ISSUE THREAD

**Issue by timkgh** [dnakov/little-rat#27]
I blocked a specific URL for an extension:

<img width="205" alt="28227" src="https://github.com/dnakov/little-rat/assets/23507658/a384b61a-392d-49f5-96e4-b0bf3495241a">

But I still see DNS requests on my router for `o1388847.ingest.sentry.io` coming from this extension instance (if I disable the extension, the requests stop) and also actual network traffic to/from the IP the name resolves to, captured with `tcpdump`.

I did the full manual installation from this repo, not from the Chrome extension store.

**Comment by dnakov** [comment]
To be honest, i haven't tried blocking by individual urls myself. Does blocking all still work? Now I'm worried that a chrome update might decided to prevent this, i'll have to look later

**Comment by timkgh** [comment]
No, blocking the entire extension does not work either, I still see network traffic.

**Comment by dnakov** [comment]
Strange. I just tested it on multiple extensions, both URL and All work (latest chrome Version 125.0.6422.61 (Official Build) (arm64)).
Can you try reinstalling and blocking some other extensions too?
Also, your chrome version.

**Comment by timkgh** [comment]
Same version 125.0.6422.61 (Official Build) (arm64)

I can't get it to block. Maybe some other extension interferes, e.g. Proxy SwitchyOmega (though this one is not active, not using a proxy)?

**Comment by dnakov** [comment]
I have a simple test extension that just does fetch(url). URL is a remote host that I have access to and can look at incoming requests. I can also see that the fetch fails by looking at the error log of that test extension
[test.zip](https://github.com/dnakov/little-rat/files/15382773/test.zip)

Do you have any other profiles open that could have that extension open?
I'm gonna try Unclutter in a few.

**Comment by timkgh** [comment]
> Do you have any other profiles open that could have that extension open?

I do not.

**Comment by dnakov** [comment]
<img width="384" alt="Screenshot 2024-05-20 at 8 17 17 PM" src="https://github.com/dnakov/little-rat/assets/3777433/8ffbbc77-b7d0-4643-922c-0aaee02373f6">
Just tried with Unclutter. This is its the service-worker erroring once I blocked it.

**Comment by dnakov** [comment]
<img width="1458" alt="Screenshot 2024-05-20 at 8 21 38 PM" src="https://github.com/dnakov/little-rat/assets/3777433/d5f2ef97-a636-4f5c-8344-f383ceafa1fe">
Unblocked, then blocked.
Can you try this on your end, go to Manage extensions, find Unclutter, click the service-worker.js link. This will open up its devtools, go to the network tab. Unblock it, click on the Unclutter extension icon, that triggers a request. Then block it and repeat, you should see it in red.

**Comment by timkgh** [comment]
Mine shows a different error and it gets a 429 from Sentry:
```
{
    "detail": "Sentry dropped data due to a quota or internal rate limit being reached. This will not affect your application. See https://docs.sentry.io/product/accounts/quotas/ for more information."
}
```

<img width="438" alt="13553" src="https://github.com/dnakov/little-rat/assets/23507658/8c72e21a-7ccd-470a-8e78-39cb92378e30">

**Comment by dnakov** [comment]
It should say blocked in the network tab, but doesn't look like it.
It's possible you have some other extension that explicitly allows all calls from extensions via a rule, which could invalidate this blocking rule. Can you try in a new profile without other extensions?

**Comment by timkgh** [comment]
Hmm, maybe it does work. I can get it to block retrieving content from the site that it's trying to unclutter when I click on the Unclutter icon. That part works. But there seem to be some calls to Sentry that happen in the _background_, on a regular basis and those do not get blocked (they just happen to get a 429 from Sentry, but that's a different issue with the dev's Sentry account).

**Comment by dnakov** [comment]
A lot of websites and apps use sentry for tracking, could be from anywhere. little-rat just blocks extensions.
