### ISSUE TITLE
Can I view detail on each network call ?

### ISSUE THREAD

**Issue by ttpro1995** [dnakov/little-rat#6]
Can I view, something similar to developer console ? (i.e: content, response, status code ...)

**Comment by dnakov** [comment]
That's not currently possible with the declarativeNetRequest API. (See screenshot of all that's available)
It could be done with the webRequest API but you won't be able to see other extension's network calls with it.
<img width="391" alt="Screenshot 2023-08-15 at 9 35 50 AM" src="https://github.com/dnakov/little-rat/assets/3777433/59e004af-d713-4b0b-b486-cc3bec371480">
