### ISSUE TITLE
 Feature request: Firefox support?

### ISSUE THREAD

**Issue by Fadyio** [dnakov/little-rat#8]
Any plans to support Firefox?

**Comment by dnakov** [comment]
Yeah, but unfortunately firefox hasn't implemented `declarativeNetRequest.onRuleMatchedDebug`
I don't know of any other way to do it

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/declarativeNetRequest/onRuleMatchedDebug
https://bugzilla.mozilla.org/show_bug.cgi?id=1745773

**Comment by dnakov** [comment]
While we can't see the requests in FF, I think we can block them. 
I'm not sure how useful that'd be. The extension won't be able to give you any feedback but it could allow you to just block network requests for a particular extension (or all.)
I haven't tried it, but you can probably do that with uBlock Origin already using custom rules.

**Comment by nicoleahmed** [comment]
Ah that's interesting I wasn't sure if UBO was working with extension traffic.

So it might be the case that requests are made but then blocked by UBO
Little rat would show these?

**Comment by dnakov** [comment]
In Firefox, I can't even filter requests originating from other extensions, no matter what I try.

**Comment by dnakov** [comment]
Closing this, I don't see a way of making this work in FF. Reopen if you have any ideas

**Comment by virginviolet** [comment]
There is probably a security benefit in not allowing extensions to spy on each other. But, if that's the route Mozilla is going for, I think they should implement the functionality of Little rat into the browser itself. Someone write a feature request?
