### ISSUE TITLE
Feature request: Whitelist blacklist options

### ISSUE THREAD

**Issue by nicoleahmed** [dnakov/little-rat#9]
Hey 
Just posting my twitter comment here

Works great for me- easy to use. Could we add option to whitelist certain sites to help bring the "red number counter" down. Also wonder if we can add blacklist of malicious sites - the counter could be red for these, and amber for unknown? Green for whitelist?...Blocking?

I see that you've discussed blocking on another issue which sounds complex 

But atleast a colour indicator for known bad sites would be a step towards that 

Like I've mentioned [here](https://github.com/dnakov/little-rat/issues/8#issuecomment-1681771584)  I don't think UBO blocks extension traffic so we are vulnerable to it

**Comment by dnakov** [comment]
closing, see #1
